/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: this file is auto-generated by `next dev`/`next build` — do not edit it by hand.
// It's checked in here only so the scaffold type-checks before the first local `pnpm dev` run.
